#!/bin/bash

set -e

cat << 'EOF'
 _                                         _
| |    ___ _ __ ___   ___  _ __   ___ __ _| | _____
| |   / _ | '_ ` _ \ / _ \| '_ \ / __/ _` | |/ / _ \
| |__|  __| | | | | | (_) | | | | (_| (_| |   |  __/
|_____\___|_| |_| |_|\___/|_| |_|\___\__,_|_|\_\___|


EOF

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 {run|build|clean|help}"
    exit 1
fi

function build() {
    mkdir -p bin/esp/efi/boot

    command_exists() {
        command -v "$1" >/dev/null 2>&1
    }

    cargo build
    cp target/x86_64-unknown-uefi/debug/lemoncake-bootloader.efi bin/esp/efi/boot/bootx64.efi
    cd kernel
    ./build
    cp target/kernel.bin ../bin/esp/kernel
    cd ..

    if command_exists python; then
        python check_header.py bin/esp/kernel
    elif command_exists python3; then
        python3 check_header.py bin/esp/kernel
    else
        echo "Python not installed. Skipping header check..."
    fi

    #if [ linker.ld -nt bin/kernel.bin ] || [ bin/boot.o -nt bin/kernel.bin ] || [ bin/liblemoncake.a -nt bin/kernel.bin ] || [ bin/kernel.bin -nt lemoncake.iso ] || [ grub.cfg -nt lemoncake.iso ]; then
    #    ld -n -o bin/kernel.bin -T linker.ld bin/boot.o bin/liblemoncake.a
    #    mkdir -p bin/iso/boot/grub
    #
    #    cp grub.cfg bin/iso/boot/grub/
    #    cp bin/kernel.bin bin/iso/boot/
    #
    #    grub2-mkrescue -o lemoncake.iso bin/iso
    #fi
}

function run() {
    build
    #if [ ! -f hd.img ]; then
    #    echo "Creating hard drive image..."
    #    qemu-img create hd.img 128M
    #fi

    if [ ! -f bin/OVMF.fd ]; then
        cp /usr/share/OVMF/x64/OVMF.fd bin/OVMF.fd
    fi
    qemu-system-x86_64 -enable-kvm -bios bin/OVMF.fd -drive format=raw,file=fat:rw:bin/esp -m 256M -D qemu_log.log -d in_asm,int,cpu_reset -cpu host -serial stdio
}

function clean() {
    rm -rf bin/ target/ *.iso
}

case "$1" in
    run)
        run
        ;;

    build)
        build
        ;;
    
    clean)
        clean
        ;;
        
    help)
        echo "Usage: $0 {run|build|clean|help}"
        echo "  run   - Run Lemoncake"
        echo "  build - Build Lemoncake"
        echo "  clean - Clean the workspace"
        echo "  help  - Display this message"
        ;;
        
    *)
        echo "Error: Invalid argument '$1'"
        echo "Usage: $0 {run|build|help}"
        exit 1
        ;;
        
esac
