[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
spin = "0.10.0"
uart_16550 = "0.3.2"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
x86_64 = "0.15.2"

[profile.dev]
panic = "abort"
debug = true

[profile.release]
panic = "abort"
debug = true