name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install NASM
      run: |
        sudo apt update
        sudo apt install -y nasm
    - uses: actions/checkout@v4
    - name: Run utility script
      run: python utils.py
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    
