name: Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install QEMU & OVMF
      run: sudo apt-get update && sudo apt-get install -y qemu ovmf
      
    - uses: actions/checkout@v4
    - name: Build
      run: ./build build --release
